### ISSUE TITLE
rename files on vscode

### ISSUE THREAD

**Issue by jessicaliiu** [jessicaliiu/gelp-me-please#8]
help. i dont know how to add more files for different pages. also i don't know how to rename them.

**Comment by MangoSwirl** [comment]
You can add new files with the ![plus](https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/light/new-file.svg) button at the top of the ![explorer](https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/light/files.svg) sidebar and rename them by right-clicking them or using the enter key.
